### ISSUE TITLE
would you please add this package to stackage?

### ISSUE THREAD

**Issue by winterland1989** [redneb/HsOpenSSL-x509-system#1]
I'd like to add this package to [stackage](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md), so that packages depend on it can be added too ; )

**Comment by redneb** [comment]
Hi, thanks for the report. I submitted a PR for that: https://github.com/fpco/stackage/pull/1803.

**Comment by winterland1989** [comment]
Thanks!

**Comment by redneb** [comment]
The PR was merged.
